"""Initial migration

Revision ID: bb3cc8b0d3d9
Revises: 
Create Date: 2025-07-23 20:13:24.366604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb3cc8b0d3d9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banka_islem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('banka_adi', sa.String(length=255), nullable=False),
    sa.Column('hesap_no', sa.String(length=50), nullable=True),
    sa.Column('islem_tipi', sa.String(length=20), nullable=False),
    sa.Column('tutar', sa.Float(), nullable=False),
    sa.Column('doviz_tipi', sa.String(length=10), nullable=True),
    sa.Column('kur', sa.Float(), nullable=True),
    sa.Column('referans_no', sa.String(length=100), nullable=True),
    sa.Column('tarih', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_banka_islem_id'), 'banka_islem', ['id'], unique=False)
    op.create_table('cari_kayit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cari_ad', sa.String(length=255), nullable=False),
    sa.Column('cari_tipi', sa.String(length=50), nullable=True),
    sa.Column('islem_tipi', sa.String(length=20), nullable=True),
    sa.Column('tutar', sa.Float(), nullable=False),
    sa.Column('doviz_tipi', sa.String(length=10), nullable=True),
    sa.Column('kur', sa.Float(), nullable=True),
    sa.Column('referans_no', sa.String(length=100), nullable=True),
    sa.Column('stok_referans_id', sa.Integer(), nullable=True),
    sa.Column('tarih', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('odeme_vadesi', sa.DateTime(timezone=True), nullable=True),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cari_kayit_id'), 'cari_kayit', ['id'], unique=False)
    op.create_table('doviz_kuru',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doviz_kodu', sa.String(length=10), nullable=False),
    sa.Column('alis_kuru', sa.Float(), nullable=False),
    sa.Column('satis_kuru', sa.Float(), nullable=False),
    sa.Column('tarih', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('kaynak', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doviz_kuru_id'), 'doviz_kuru', ['id'], unique=False)
    op.create_table('gelir_kaydi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kategori', sa.String(length=100), nullable=False),
    sa.Column('alt_kategori', sa.String(length=100), nullable=True),
    sa.Column('tutar', sa.Float(), nullable=False),
    sa.Column('doviz_tipi', sa.String(length=10), nullable=True),
    sa.Column('kur', sa.Float(), nullable=True),
    sa.Column('referans_no', sa.String(length=100), nullable=True),
    sa.Column('tarih', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gelir_kaydi_id'), 'gelir_kaydi', ['id'], unique=False)
    op.create_table('gider_kaydi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kategori', sa.String(length=100), nullable=False),
    sa.Column('alt_kategori', sa.String(length=100), nullable=True),
    sa.Column('tutar', sa.Float(), nullable=False),
    sa.Column('doviz_tipi', sa.String(length=10), nullable=True),
    sa.Column('kur', sa.Float(), nullable=True),
    sa.Column('referans_no', sa.String(length=100), nullable=True),
    sa.Column('tarih', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gider_kaydi_id'), 'gider_kaydi', ['id'], unique=False)
    op.create_table('kasa_islem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('islem_tipi', sa.String(length=20), nullable=False),
    sa.Column('kategori', sa.String(length=100), nullable=False),
    sa.Column('tutar', sa.Float(), nullable=False),
    sa.Column('doviz_tipi', sa.String(length=10), nullable=True),
    sa.Column('kur', sa.Float(), nullable=True),
    sa.Column('cari_id', sa.Integer(), nullable=True),
    sa.Column('referans_no', sa.String(length=100), nullable=True),
    sa.Column('tarih', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kasa_islem_id'), 'kasa_islem', ['id'], unique=False)
    op.create_table('musteri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=255), nullable=False),
    sa.Column('telefon', sa.String(length=20), nullable=True),
    sa.Column('adres', sa.Text(), nullable=True),
    sa.Column('ulke', sa.String(length=100), nullable=True),
    sa.Column('vergi_no', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_musteri_id'), 'musteri', ['id'], unique=False)
    op.create_table('tedarikci',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=255), nullable=False),
    sa.Column('telefon', sa.String(length=20), nullable=True),
    sa.Column('adres', sa.Text(), nullable=True),
    sa.Column('vergi_no', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tedarikci_id'), 'tedarikci', ['id'], unique=False)
    op.create_table('urun',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=255), nullable=False),
    sa.Column('kategori', sa.String(length=100), nullable=True),
    sa.Column('birim', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_urun_id'), 'urun', ['id'], unique=False)
    op.create_table('stok_kaydi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('urun_id', sa.Integer(), nullable=False),
    sa.Column('tedarikci_id', sa.Integer(), nullable=False),
    sa.Column('miktar', sa.Float(), nullable=False),
    sa.Column('birim_fiyat', sa.Float(), nullable=False),
    sa.Column('toplam_fiyat', sa.Float(), nullable=False),
    sa.Column('doviz_tipi', sa.String(length=10), nullable=True),
    sa.Column('lokasyon', sa.String(length=100), nullable=True),
    sa.Column('adres_adi', sa.String(length=255), nullable=True),
    sa.Column('plaka', sa.String(length=20), nullable=True),
    sa.Column('sofor_ad', sa.String(length=100), nullable=True),
    sa.Column('sofor_telefon', sa.String(length=20), nullable=True),
    sa.Column('protein', sa.Float(), nullable=True),
    sa.Column('hektolitre', sa.Float(), nullable=True),
    sa.Column('rutubet', sa.Float(), nullable=True),
    sa.Column('hasere', sa.Float(), nullable=True),
    sa.Column('embriyo', sa.Float(), nullable=True),
    sa.Column('donme', sa.Float(), nullable=True),
    sa.Column('yabanci_madde', sa.Float(), nullable=True),
    sa.Column('kepce_ucreti', sa.Float(), nullable=True),
    sa.Column('hamal_ucreti', sa.Float(), nullable=True),
    sa.Column('nakliye_ucreti', sa.Float(), nullable=True),
    sa.Column('fatura_ucreti', sa.Float(), nullable=True),
    sa.Column('fatura_alici', sa.String(length=20), nullable=True),
    sa.Column('tarih', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('odeme_vadesi', sa.DateTime(timezone=True), nullable=True),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['tedarikci_id'], ['tedarikci.id'], ),
    sa.ForeignKeyConstraint(['urun_id'], ['urun.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stok_kaydi_id'), 'stok_kaydi', ['id'], unique=False)
    op.create_table('stok_cikis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stok_kaydi_id', sa.Integer(), nullable=False),
    sa.Column('musteri_id', sa.Integer(), nullable=False),
    sa.Column('miktar', sa.Float(), nullable=False),
    sa.Column('birim_fiyat', sa.Float(), nullable=False),
    sa.Column('toplam_fiyat', sa.Float(), nullable=False),
    sa.Column('doviz_tipi', sa.String(length=10), nullable=True),
    sa.Column('cikis_tipi', sa.String(length=20), nullable=True),
    sa.Column('lokasyon', sa.String(length=100), nullable=True),
    sa.Column('plaka', sa.String(length=20), nullable=True),
    sa.Column('sofor_ad', sa.String(length=100), nullable=True),
    sa.Column('sofor_telefon', sa.String(length=20), nullable=True),
    sa.Column('kepce_ucreti', sa.Float(), nullable=True),
    sa.Column('hamal_ucreti', sa.Float(), nullable=True),
    sa.Column('nakliye_ucreti', sa.Float(), nullable=True),
    sa.Column('fatura_ucreti', sa.Float(), nullable=True),
    sa.Column('gumruk_ucreti', sa.Float(), nullable=True),
    sa.Column('fatura_alici', sa.String(length=20), nullable=True),
    sa.Column('tarih', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('odeme_vadesi', sa.DateTime(timezone=True), nullable=True),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['musteri_id'], ['musteri.id'], ),
    sa.ForeignKeyConstraint(['stok_kaydi_id'], ['stok_kaydi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stok_cikis_id'), 'stok_cikis', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stok_cikis_id'), table_name='stok_cikis')
    op.drop_table('stok_cikis')
    op.drop_index(op.f('ix_stok_kaydi_id'), table_name='stok_kaydi')
    op.drop_table('stok_kaydi')
    op.drop_index(op.f('ix_urun_id'), table_name='urun')
    op.drop_table('urun')
    op.drop_index(op.f('ix_tedarikci_id'), table_name='tedarikci')
    op.drop_table('tedarikci')
    op.drop_index(op.f('ix_musteri_id'), table_name='musteri')
    op.drop_table('musteri')
    op.drop_index(op.f('ix_kasa_islem_id'), table_name='kasa_islem')
    op.drop_table('kasa_islem')
    op.drop_index(op.f('ix_gider_kaydi_id'), table_name='gider_kaydi')
    op.drop_table('gider_kaydi')
    op.drop_index(op.f('ix_gelir_kaydi_id'), table_name='gelir_kaydi')
    op.drop_table('gelir_kaydi')
    op.drop_index(op.f('ix_doviz_kuru_id'), table_name='doviz_kuru')
    op.drop_table('doviz_kuru')
    op.drop_index(op.f('ix_cari_kayit_id'), table_name='cari_kayit')
    op.drop_table('cari_kayit')
    op.drop_index(op.f('ix_banka_islem_id'), table_name='banka_islem')
    op.drop_table('banka_islem')
    # ### end Alembic commands ###
